server:
  port: ${APP_PORT:8080}
  
spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB_NAME:groschn}

      
blockchain:
  node:
    credentials:
      public-key: ${NODE_PUBLIC_KEY:PZ8Tyr4Nx8MHsRAGMpZmZ6TWY63dXWSCwN3VGoADiKCrxqDdUeowvmxoCcEQoVNX63Mo9RYeRNLPSjnrHQpyQFeho1Kz8xu4dxX4nR8MB2NkeAxH74uM2LDp}
      private-key: ${NODE_PRIVATE_KEY:3hupFSQNWwiJuQNc68HiWzPgyNpQA2yy9iiwhytMS7rZyXaRCMKct5L7sHaT9ZNgYUjgMeVh4vNN9xcM5LZpUcVzXkV5Hn4thLSNwwormNNdxSAjQ8BBAyNdpP51iG9SN93BwRzVFFeMyg1HWruNZgRhgskz2AoTU2VrbCJ2zrdQUUYR2MU13471c9DJSQH3zmNPU}
  punch-timer:
    initial-delay: 20000
    punch-rate: 15000
    process-timeout-seconds: 45
  messaging:
   id-cache:
     expire-after-milliseconds: 600000
     initial-capacity: 1000
     max-capacity: 50000
    
# message protocol configuration
atomix:
  host-node-address: ${ATOMIX_NODE_ADDR:localhost:1234}
  discovery:
    heartbeat-milliseconds: ${ATOMIX_HEARTBEAT_INTERVAL:1000}
    failure-timeout-milliseconds: ${ATOMIX_MULTICAST_FAILURE_TIMEOUT:20000}
    bootstrap-nodes:
      - {name: 'master1', address: 'localhost:1001'}
      - {name: 'master2', address: 'localhost:1002'}
      - {name: 'master3', address: 'localhost:1003'}
  partition-group:
    number-partitions: ${ATOMIX_PARTITION_GROUP_SIZE:23}
    name: ${ATOMIX_PARTITION_GROUP_NAME:data}