server:
  port: ${APP_PORT:8080}
  
spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: 0
      database: ${MONGO_DB_NAME:groschn}

      
blockchain:
  node:
    id: ${NODE_ID:groschn-master-123}
  punch-timer:
    initial-delay: 20000
    punch-rate: 15000
    process-timeout-seconds: 21
  messaging:
    thread-pool:
      size: 10
    id-cache:
      expire-after-milliseconds: 600000
      initial-capacity: 10
      max-capacity: 20