server:
  port: ${APP_PORT:8080}
  
spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: 0
      database: ${MONGO_DB_NAME:groschn}

      
blockchain:
  punch-timer:
    initial-delay: 20000
    punch-rate: 15000
    process-timeout-seconds: 21